### ISSUE TITLE
Translation of the slides

### ISSUE THREAD

**Issue by fernandomayer** [kevinushey/2020-rstudio-conf#1]
Hi,

I was preparing myself to make a presentation of `renv`, however, your slides are just perfect and I couldn't do any better than this. But I would need to present them in Portuguese.

Would it be fine if I fork this repo and just translate the slides into (Brazilian) Portuguese? Of course I will keep your name as the original author (I would just be a "translator").

Thanks for `renv` and this slides.

**Comment by kevinushey** [comment]
Thank you! Please feel free.

**Comment by fernandomayer** [comment]
That's great! Thanks!
